export const localImages = {
  ALOE: require("./assets/ALOE.png"),
  "HEARTLEAF PHILODENDRON": require("./assets/HEARTLEAF_PHILODENDRON.png"),
  "BIRDS NEST FERN": require("./assets/BIRDS_NEST_FERN.png"),
  "ZZ RAVEN": require("./assets/ZZ_RAVEN.png"),
  ANTHURIUM: require("./assets/ANTHURIUM.png"),
  "ARECA PALM": require("./assets/ARECA_PALM.png"),
  "BOSTON FERN": require("./assets/BOSTON_FERN.png"),
  "CHRISTMAS CACTUS": require("./assets/CHRISTMAS_CACTUS.png"),
  DIEFFENBACHIA: require("./assets/DIEFFENBACHIA.png"),
  DRACAENA: require("./assets/DRACAENA.png"),
  FITTONIA: require("./assets/FITTONIA.png"),
  GUZMANIA: require("./assets/GUZMANIA.png"),
  HOYA: require("./assets/HOYA.png"),
  "LUCKY BAMBOO": require("./assets/LUCKY_BAMBOO.png"),
  ORCHID: require("./assets/ORCHID.png"),
  SCHEFFLERA: require("./assets/SCHEFFLERA.png"),
  STRELITZIA: require("./assets/STRELITZIA.png"),
  ALOCASIA: require("./assets/ALOCASIA.png"),
  HAWORTHIA: require("./assets/HAWORTHIA.png"),
  "JADE PLANT": require("./assets/JADE_PLANT.png"),
  KALANCHOE: require("./assets/KALANCHOE.png"),
  "SNAKE PLANT": require("./assets/SNAKE_PLANT.png"),
  "SPIDER PLANT": require("./assets/SPIDER_PLANT.png"),
  CROTON: require("./assets/CROTON.png"),
  "CAST IRON PLANT": require("./assets/CAST_IRON_PLANT.png"),
  "CHINESE EVERGREEN": require("./assets/CHINESE_EVERGREEN.png"),
  "PARLOR PALM": require("./assets/PARLOR_PALM.png"),
  "PEACE LILY": require("./assets/PEACE_LILY.png"),
  "PRAYER PLANT": require("./assets/PRAYER_PLANT.png"),
  "AFRICAN VIOLET": require("./assets/AFRICAN_VIOLET.png"),
};