

export const plants = [
  {
    name: "Aloe Vera",
    image: "ALOE",
    plantId: 2,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "AloeDetails",
    description: "Size: 12 to 24 inches tall Water: Water deeply, but not too often, allowing the soil to dry to a depth of 1 to 2 inches between watering. Fertilize: Aloes generally don't require fertilizing. Description:  Aloes prefer tight quarters and keeping them slightly root bound may help promote blooming, which doesn't always happen when they are grown indoors. Grow them in a sandy, well-drained soil such as a cactus potting mix. Aloe is a cactus-like plant that grows in hot, dry climates. Historically, it was used for skin conditions and was thought to promote wound healing. Aloe products can be made from the gel (inner leaf), latex (outer layer), or whole crushed leaf. The International Agency for Research on Cancer has classified whole leaf extract of aloe vera as a possible carcinogen in humans.",
  },
   {
    name: "Philodendron",
    image: "HEARTLEAF PHILODENDRON",
    plantId: 3,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "PhilodendronDetails",
    description: "Size: Vines to 8 feet long. Water: Prefers evenly moist soil, but not soggy. Water if top inch of soil is dry.Fertilize: Apply a water-soluble houseplant fertilizer from spring through fall.Description:  Another very easy-to-grow houseplant, similar to pothos. Tolerates low light, but will grow faster in medium to bright light. Foliage comes in a variety of sizes, shapes, and colors. Philodendrons can also be grown outdoors in mild climates. Philodendrons are tropical evergreen perennials native to Central and South America, belonging to the same family as pothos plants (Araceae). There are hundreds of philodendron species, categorized as either vining or non-climbing. Vining types have aerial roots and are excellent for hanging baskets or climbing. Philodendrons are considered mildly poisonous to people and pets if ingested, containing calcium oxalate crystals that can cause irritation.",
  },
  {
    name: "Bird's Nest Fern",
    image: "BIRDS NEST FERN",
    plantId: 4,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "BirdsNestFernDetails",
    description: "Size: Up to 2 feet tall. Water: Keep soil evenly moist, but not soggy. Water at the edge of the rosette so water doesn't pool in the center and cause rot. Yellow leaves signal overwatering.Fertilize: Fertilize every 2 to 4 weeks from spring until fall with a diluted houseplant fertililzer.Description:  This tropical fern makes a stunning centerpiece for a table or plant stand. New fronds unfurl from the center of the plant, so the shape remains elegant and upright. An ideal plant for a steamy bathroom, bird's nest ferns like moderate humidity and temperatures around 70 degrees F. The scientific name is Asplenium nidus, and it is an epiphytic species of fern in the family Aspleniaceae. It is native to tropical southeastern Asia, eastern Australia, Hawaii, Polynesia, Christmas Island, India, and eastern Africa. Epiphytic means it naturally grows on the surface of another plant.",
  },
    {
    name: "ZZ Raven",
    image: "ZZ RAVEN",
    plantId: 5,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "ZZRavenDetails",
    description: "Size: 2 to 3 feet tall.Water: Allow the soil to dry out completely between waterings, as it stores water in its rhizomes. Overwatering is a common issue.Fertilize: Fertilize sparingly, every 3-4 months during the growing season with a balanced liquid fertilizer. Description:   The ZZ Raven Plant is a distinctive cultivar of the ZZ plant, also known as Zamioculcas zamiifolia Raven. Its most striking feature is its foliage, which emerges in a vibrant lime-green color and gradually matures to a deep, almost black, glossy hue. Like the classic ZZ plant, 'Raven' is exceptionally hardy and tolerant of neglect, thriving in low to bright indirect light and requiring infrequent watering due to its drought-tolerant nature. This makes it an excellent choice for beginners or those seeking a low-maintenance, unique-looking plant.",
  },
   {
    name: "Anthurium",
    image: "ANTHURIUM",
    plantId: 6,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "AnthuriumDetails",
    description: "Size: 1 to 3 feet tall and wide. Water: Keep the soil consistently moist but not soggy. Allow the top inch of soil to dry out between waterings.Fertilize: Fertilize every 6-8 weeks during the growing season with a diluted liquid houseplant fertilizer.Description:  Anthuriums are tropical evergreen plants native to the rainforests of Central and South America. They are widely cultivated for their striking, heart-shaped, waxy flowers, which are actually modified leaves called spathes. These spathes come in brilliant shades of red, pink, white, or purple, and typically surround a prominent, cylindrical spadix. Anthuriums thrive in bright, indirect light and require high humidity, making them ideal for bathrooms or kitchens with good natural light.",
  },  
  {
    name: "Areca Palm",
    image: "ARECA PALM",
    plantId: 7,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "ArecaPalmDetails",
    description: "Size: Can reach 6 to 12 feet tall indoors.Water: Keep soil consistently moist but not soggy during the growing season; allow the top inch to dry out between waterings in winter.Fertilize: Fertilize monthly during spring and summer with a liquid houseplant fertilizer diluted to half strength.Description:  The Areca Palm, also known as Butterfly Palm, is a popular houseplant recognized for its graceful, feathery fronds that emerge from multiple cane-like stems. Native to Madagascar, it contributes to a tropical aesthetic indoors and can act as a natural air humidifier. This palm prefers bright, indirect light and can suffer from brown tips if humidity is too low or if it experiences inconsistent watering. It is a slow to moderate grower, typically adding 6-10 inches of height per year.",
  },  
   {
    name: "Boston Fern",
    image: "BOSTON FERN",
    plantId: 8,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "BostonFernDetails",
    description: "Size: 2 to 3 feet tall and wide.Water: Keep the soil consistently moist but not soggy. Avoid letting the soil dry out completely.Fertilize: Fertilize monthly during the growing season (spring through fall) with a diluted liquid houseplant fertilizer.Description:   The Boston Fern is a classic and popular houseplant, celebrated for its arching, bright green fronds. Native to tropical and subtropical regions worldwide, it typically grows epiphytically or terrestrially in humid environments. This fern requires high humidity to prevent its delicate fronds from drying out and turning brown; regular misting or placement near a humidifier is beneficial. It prefers bright, indirect light and consistent temperatures to maintain its lush appearance.",
  },  
  {
    name: "Christmas Cactus",
    image: "CHRISTMAS CACTUS",
    plantId: 9,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "ChristmasCactusDetails",
    description: "Size: 6 to 12 inches tall, with cascading stems.Water: Water when the top inch of soil is dry. Reduce watering after blooming.Fertilize: Fertilize every 2-4 weeks during spring and summer with a balanced liquid fertilizer; cease fertilizing in early fall to encourage blooming.Description:  The Christmas Cactus is an epiphytic succulent native to the coastal mountains of southeastern Brazil. Unlike desert cacti, it grows in humid forests, often on trees or rocks, and is characterized by its flattened, segmented stems. This plant is renowned for its vibrant, tubular flowers that bloom in late fall or early winter, making it a popular holiday plant. Flowers can be pink, red, white, orange, or purple. It thrives in bright, indirect light and cool temperatures (around 50-55°F or 10-13°C) in the fall to initiate blooming.",
  },
  {
    name: "Dieffenbachia",
    image: "DIEFFENBACHIA",
    plantId: 10,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "DieffenbachiaDetails",
    description: "Size: 2 to 6 feet tall. Water: Keep the soil consistently moist but not soggy. Allow the top inch of soil to dry slightly before rewatering. Fertilize: Fertilize monthly during the growing season (spring and summer) with a balanced liquid houseplant fertilizer. Description:   Dieffenbachia, often called Dumb Cane, is a tropical perennial native to the rainforests of Central and South America. It is highly valued for its large, broad, oblong leaves that come in striking patterns of green, cream, and yellow variegation. While an attractive foliage plant, all parts of the Dieffenbachia contain calcium oxalate crystals, which can cause irritation and temporary swelling of the tongue and throat if ingested, hence its common name 'Dumb Cane'. It thrives in medium to bright indirect light and appreciates consistent humidity.",
  },  
  {
    name: "Dracaena",
    image: "DRACAENA",
    plantId: 11,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "DracaenaDetails",
    description: "Size: Varies greatly by species, from 1 to 10 feet tall indoors. Water: Allow the top inch or two of soil to dry out between waterings. Avoid overwatering, which can lead to root rot. Fertilize: Fertilize every 2-4 weeks during the growing season (spring and summer) with a balanced liquid houseplant fertilizer. Description:   Dracaena is a diverse genus of evergreen trees and shrubs native to Africa, Asia, and Central America, encompassing many popular indoor plant species like Dracaena fragrans (Corn Plant) and Dracaena marginata (Dragon Tree). These plants are valued for their upright growth habit and sword-like or strap-shaped leaves, which often feature vibrant variegation. Dracaenas are known for their resilience and ability to tolerate a range of indoor conditions, making them excellent choices for beginners.",
  },  
  { 
    name: "Fittonia",
    image: "FITTONIA",
    plantId: 12,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "FittoniaDetails",
    description: "Size: 6 to 12 inches tall with a spreading habit. Water: Keep the soil consistently moist but not waterlogged. Fittonia is prone to wilting if allowed to dry out completely. Fertilize: Fertilize monthly during the growing season with a diluted liquid houseplant fertilizer. Description:   Fittonia, commonly known as Nerve Plant or Mosaic Plant, is a tropical evergreen perennial native to the rainforests of South America. It is prized for its intricate, contrasting vein patterns that stand out against its green leaves, available in shades of white, pink, or red. This low-growing plant thrives in high humidity and warm temperatures, making it an excellent choice for terrariums or humid bathroom environments. Fittonia can be a bit dramatic, often wilting rapidly when thirsty, but typically revives quickly after watering.", 
  },
  {    
    name: "Guzmania",
    image: "GUZMANIA",
    plantId: 13,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "GuzmaniaDetails",
    description: "Size: 1 to 2 feet tall, including flower stalk. Water: Keep the central cup (tank) filled with distilled or rainwater, flushing it out every few weeks. Water the soil sparingly. Fertilize: Fertilize lightly by adding a diluted liquid fertilizer to the central cup or spraying it on the leaves. Description:   Guzmania is a genus of epiphytic bromeliads native to the tropical rainforests of Central and South America. These plants are grown for their vibrant, long-lasting inflorescences, which are actually colorful bracts (modified leaves) that surround inconspicuous, true flowers. The bracts can display brilliant shades of red, orange, yellow, or pink, providing a stunning pop of color. As epiphytes, Guzmanias primarily absorb water and nutrients through their leaves, especially through the central cup formed by their rosette of foliage.",
  },
  {
    name: "Hoya",
    image: "HOYA",
    plantId: 14,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "HoyaDetails",
    description: "Size: Vines can reach 6 to 10 feet long. Water: Allow the soil to dry out completely between waterings. Overwatering can lead to root rot. Fertilize: Fertilize sparingly, every 2-4 weeks during the growing season, with a diluted liquid fertilizer. Description:   Hoya carnosa, commonly known as Wax Plant or Porcelain Flower, is a popular evergreen vining plant native to East Asia and Australia. It is cherished for its thick, waxy, succulent-like leaves and its clusters of fragrant, star-shaped flowers that often appear waxy or porcelain-like. The flowers frequently produce a sweet, sticky nectar. Hoyas are relatively low-maintenance, drought-tolerant, and prefer bright, indirect light, making them excellent choices for hanging baskets or training on a trellis.",
  },
  {
    name: "Lucky Bamboo",
    image: "LUCKY BAMBOO",
    plantId: 15,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "LuckyBambooDetails",
    description: "Size: Varies widely based on training, typically 6 inches to 3 feet tall. Water: If grown in water, change the water weekly. If grown in soil, keep it consistently moist but not waterlogged. Fertilize: Fertilize sparingly; a very diluted liquid fertilizer every couple of months is sufficient for soil-grown plants, while water-grown plants may benefit from a specialized lucky bamboo fertilizer. Description:   Lucky Bamboo is not a true bamboo but a species of Dracaena, native to Cameroon in West Africa. It is often cultivated for its ornamental value, with stems that can be trained into intricate spirals, braids, or tiers. This plant is remarkably tolerant of low light conditions and can be grown purely in water, provided the roots are submerged. It is a popular gift and feng shui element, believed to bring good fortune to the household.",
  },
  {
    name: "Orchid",
    image: "ORCHID",
    plantId: 16,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "OrchidDetails",
    description: "Size: Typically 1 to 3 feet tall, with flower spikes reaching higher. Water: Water when the potting medium is dry to the touch, often every 7-10 days. Avoid overwatering. Fertilize: Use a balanced orchid fertilizer diluted to half strength every 2-4 weeks, especially during active growth. Description:   Phalaenopsis orchids, commonly known as Moth Orchids, are epiphytic plants native to tropical Asia and Australia. They are characterized by their flattened, fleshy leaves and long-lasting, showy flowers that emerge from an arching stem. These orchids thrive in bright, indirect light conditions and prefer high humidity. Their roots are adapted to absorb moisture and nutrients from the air and rain, which is why they are often grown in bark or sphagnum moss rather than traditional soil.",
  },
  {
    name: "Schefflera",
    image: "SCHEFFLERA",
    plantId: 17,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "ScheffleraDetails",
    description: "Size: Can grow 4 to 8 feet tall indoors. Water: Water thoroughly when the top inch or two of soil feels dry. Allow excess water to drain to prevent root rot. Fertilize: Fertilize every 2-4 weeks during the growing season with a balanced liquid houseplant fertilizer. Description:   Schefflera arboricola, commonly called Dwarf Umbrella Tree, is a popular evergreen shrub native to Taiwan. It is characterized by its glossy, oval leaflets that radiate outwards from a central point, forming an umbrella-like cluster. This plant is known for its relatively easy care and adaptability, thriving in medium to bright indirect light. While it can grow quite large indoors, it can be pruned to maintain a desired size and shape, making it a versatile choice for various indoor spaces.",
  },
  {
    name: "Strelitzia",
    image: "STRELITZIA",
    plantId: 18,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "StrelitziaDetails",
    description: "Size: Can reach 3 to 6 feet tall indoors. Water: Keep soil consistently moist during the growing season; allow the top few inches to dry out before rewatering. Reduce watering in winter. Fertilize: Fertilize monthly during spring and summer with a balanced liquid houseplant fertilizer. Description:   Strelitzia reginae, commonly known as Bird of Paradise, is a stunning evergreen perennial native to South Africa. It is named for its exotic, crane-like flowers, which feature vibrant orange sepals and blue petals, resembling a bird in flight. This plant also boasts large, paddle-shaped, blue-green leaves that resemble those of a banana plant. Indoors, the Bird of Paradise requires bright, direct to indirect sunlight and ample space to accommodate its size. While it can take several years to bloom, its dramatic foliage alone makes it a popular ornamental plant.",
  },
  {
    name: "Alocasia",
    image: "ALOCASIA",
    plantId: 19,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "AlocasiaDetails",
    description: "Size: 2 to 6 feet tall and wide, depending on variety Water: Water regularly during the growing season (spring through fall) to keep the soil evenly moist, but not soggy; less frequently during winter. Fertilize: Feed with a diluted liquid houseplant fertilizer one to two times per month during spring and summer. Description:   Given the right conditions, these lush and leafy tropical plants can thrive indoors in well-lit areas, making them a bold focal point of any sunny room. In addition to bright light, alocasias also require a humid environment, so keep plants well-hydrated by using a humidifier or misting the leaves regularly. Also called Elephant Ear Plant or African Mask Plant, Alocasias have large, dark-green, glossy, heart-shaped leaves with wavy edges. Their leaves can come in red, bronze, blue-green, and purple. Alocasias are poisonous and should be kept away from pets and children.",
  },
  {
    name: "Haworthia",
    image: "HAWORTHIA",
    plantId: 20,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "HaworthiaDetails",
    description: "Size: 3 to 5 inches tallWater: Allow the soil to dry out completely between waterings.Fertilize: Infrequently, with a slow-release product.Description:  Ideal for narrow windowsills, the slow-growing succulent remains neat and compact. In summer, creamy white flowers bloom on long stems. Haworthias need almost no care and rarely need repotting. Haworthias are small succulents native primarily to South Africa. They are closely related to aloes and are in the aloe family, Aloaceae. The genus is named after Adrian Hardy Haworth, a British botanist and entomologist.",
  },
  {
    name: "Jade Plant",
    image: "JADE PLANT",
    plantId: 21,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "JadePlantDetails",
    description: "Size: Dwarf varieties, 12 to 18 inches tall.Water: Allow the soil to dry out between waterings, and water only sparingly in the winter months. Too much moisture can cause stem and root rot.Fertilize: Only occasionally with a diluted liquid fertilizer from spring through early fall.Description:  Jade plants can live for decades and are easy to propagate from leaf or stem cuttings. Let the cuttings dry out for a few days and then stick them in a good potting mix, preferably one for cactus and succulents. Also known as lucky plant, money plant, or money tree, the jade plant is a succulent plant with small pink or white flowers. It is native to the KwaZulu-Natal and Eastern Cape provinces of South Africa, and Mozambique.",
  },
  {
    name: "Kalanchoe",
    image: "KALANCHOE",
    plantId: 22,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "KalanchoeDetails",
    description: "Size: Up to 12 inches tall\n\nWater: Water every week or so when the soil feels dry.\n\nFertilize: Once or twice a year, in early spring and late autumn. Plants in bloom do not need fertilizing.\n\nDescription:\n   When kalanchoes bloom, the flowers can last for several weeks. To encourage reblooming, pinch off spent flowers and give the plant a rest period with no fertilizing and minimal watering. After a month or so, new buds should begin to form. Also known as Florist Kalanchoe, Flaming Katy, Christmas Kalanchoe, or Madagascar Widow's Thrill, this popular flowering succulent is native to Madagascar. It is admired for its striking, long-lasting blooms and glossy, dark green leaves.",
  },
  {
    name: "Snake Plant",
    image: "SNAKE PLANT",
    plantId: 22,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "SnakePlantDetails",
    description: "Size: 6 to 20 inches tall.Water: Allow the top inch of soil to dry completely before watering. Snake plants store water, so it's almost impossible to underwater them.Fertilize: Not necessary, but an occasional dose of all-purpose houseplant food during the spring and summer will encourage more vigorous growth.Description:  Also called mother-in-law's tongue, this hardy houseplant is almost impossible to kill. Although it prefers bright light, it will also persevere through dim lighting, temperature fluctuations, and lapses in watering. Snake plants were historically a recognized genus but are now included in Dracaena based on molecular phylogenetic studies. Common names include mother-in-law's tongue, devil's tongue, and bowstring hemp. Hard-leaved species typically originate from arid climates and have adaptations like thick, succulent leaves for water storage, while soft-leaved species are from tropical regions. According to a NASA Clean Air Study, Dracaena trifasciata (a former Sansevieria species) can purify air by removing pollutants like formaldehyde, xylene, and toluene.",
  },
  {
    name: "Spider Plant",
    image: "SPIDER PLANT",
    plantId: 23,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "SpiderPlantDetails",
    description: "Size: 6 to 8 inches tall, with cascading runners. Water: Water generously when the soil feels dry; more sparingly in winter.Fertilize: Monthly during the active growing season, early spring to late autumn.Description:  One of the easiest plants to propagate. Simply cut the baby spiders from their runners and place in moist potting soil. You can also stick them in a glass of water for a week or so until roots form and then pot in fresh soil. One of the easiest plants to propagate, spider plants produce 'plantlets' or 'spiderettes' on long runners. These can be easily cut and rooted in moist soil or water.",
  },
  {
    name: "Croton",
    image: "CROTON",
    plantId: 24,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "CrotonDetails",
    description: "Size: Typically 2 to 6 feet tall indoors.Water: Keep the soil consistently moist during the growing season, but allow the top inch to dry slightly before rewatering. Reduce watering in winter.Fertilize: Fertilize every 2-4 weeks during spring and summer with a balanced liquid houseplant fertilizer.Description:  Croton plants are striking broadleaf evergreens native to Malaysia, Australia, and the western Pacific Islands, where they grow as shrubs or small trees. Their most notable feature is their exceptionally colorful foliage, displaying vivid combinations of red, orange, yellow, green, and even black, often in bold patterns. To maintain their intense leaf coloration, Crotons require abundant bright, indirect sunlight. They also prefer warm temperatures and high humidity, making them somewhat sensitive to cold drafts and dry air.",
  },
  {
    name: "Cast Iron Plant",
    image: "CAST IRON PLANT",
    plantId: 25,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "CastIronPlantDetails",
    description: "Size: 15 to 24 inches tall.Water: Water moderately in spring and summer, less often in fall and winter. Allow the soil to dry between watering.Fertilize: Once a month from spring through fall.Description:  Cast iron plants are extremely slow growing and can take years to reach their full height. Cast iron plants are almost impervious to neglect and aptly named for their tough-as-nails constitution. A good choice for dimly lit rooms and rooms with northern exposure. This evergreen perennial is native to Asia. Its common name reflects its resilience; it can grow in deep shade and withstand drought.",
  },
  {
    name: "Chinese Evergreen",
    image: "CHINESE EVERGREEN",
    plantId: 26,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "ChineseEvergreenDetails",
    description: "Size: 2 to 3 feet tall.Water: Keep soil evenly moist, but not soggy. Reduce water in the winter when plant growth slows. Wilted leaves are a sign of underwatering; overwatering may cause stem or root rot.Fertilize: Monthly with a diluted liquid fertilizer from early spring through fall.Description:  Chinese evergreens hate cold drafts and temperatures below 55 degrees F (13 degrees C). They are native to tropical Asia and New Guinea and are prized for their attractive, variegated foliage that comes in shades of green, silver, and sometimes red or pink. Chinese evergreens are relatively low-maintenance and can tolerate low light conditions, making them suitable for indoor environments.",
  },
  {
    name: "Parlor Palm",
    image: "PARLOR PALM",
    plantId: 27,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "ParlorPalmDetails",
    description: "Size: 2 to 4 feet tall.Water: Avoid overwatering, but keep the soil evenly moist. Water when the surface of the soil feels dry.Fertilize: Fertilize monthly in spring and summer.Description:  Bring tropical flair indoors with a parlor palm. A popular choice for dimly lit foyers and offices. Typically the only pruning needed is the removal of lower fronds that naturally turn brown over time. Trimming healthy green fronds will stop growth completely. If you do prune, remove the entire stem. Also known as neanthe bella palm, this small, compact palm is typically single-trunked and native to rainforests from southeastern Mexico to northern Guatemala.",
  },
  {
    name: "Peace Lily",
    image: "PEACE LILY",
    plantId: 28,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "PeaceLilyDetails",
    description: "Size: 1 to 6 feet tall.Water: Keep soil evenly moist, but not soggy. Don't allow the soil to dry out completely. Reduce water in the winter when plant growth slows.Fertilize: Apply a water-soluble houseplant fertilizer at half strength every two months.Description:  Pure white spathes surrounding creamy white flower spikes bloom from mid-spring through late summer. Peace lilies love warmth and humidity. Avoid exposing them to temperatures below 55 degrees F. Despite its common name, the Peace Lily is not a true lily but a member of the Araceae family, which also includes caladiums and elephant ears. It is a tropical, evergreen plant native to Central and Southern America. The plant is mildly toxic; all parts contain calcium oxalate, which may cause stomach or respiratory irritation if consumed in large amounts. It is known for its air-purifying qualities, as identified by a NASA Clean Air Study.",
  },
  {
    name: "Prayer Plant",
    image: "PRAYER PLANT",
    plantId: 29,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "PrayerPlantDetails",
    description: "Size: Up to 3 feet tall.Water: Keep evenly moist. Don't allow to become overly soggy or dry out completely. May be sensitive to tap water, so use distilled or filtered water.Fertilize: Once a month from spring through fall.Description:  Also called rattlesnake plant, peacock plant, or zebra plant, this popular houseplant is grown for its decorative foliage in an assortment of patterns, colors, and shapes. Prayer plants don't like their roots disturbed, so repot in early spring only if rootbound. Formerly, about 200 species assigned to Calathea are now in the genus Goeppertia; Calathea currently contains around 60 species. These plants are native to the tropical Americas. Their leaves exhibit nyctinasty, folding up at night and unfurling in the morning, a process enabled by a small joint called a pulvinus. Calatheas are sensitive to minerals like chlorine and fluoride found in tap water.",
  },
  {
    name: "African Violet",
    image: "AFRICAN VIOLET",
    plantId: 30,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "AfricanVioletDetails",
    description: "Size: Usually under 4 inches tall.Water: Water when soil feels slightly dry to the touch. Try not get the leaves wet, which can cause spotting.Fertilize: Apply a specialized African violet fertilizer every 2 to 3 weeks, or according to package directions.Description: Thousands of cultivars give you a choice of almost any flower color, as well as single, double, and bicolored blooms. African violets will bloom repeatedly during spring and summer when given enough sunlight, with the blooms lasting up to a few weeks. African violets are low, compact plants that typically grow in a rosette form. They have thick, hairy green leaves and stems with velvety flowers, usually five petals (two smaller at the top, three larger at the bottom) and yellow centers. The genus Saintpaulia was named after the Swedish physician and botanist Elias Tillandz.",
  },
  {
    name: "Air Plant",
    image: "AIR PLANT",
    plantId: 31,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "AirPlantDetails",
    description: "Size: Varies, depending on the variety.Water: Run the plants under water a few times a week. If the leaves are curled more than normal, submerge in a bowl of water overnight.Fertilize: Use an epiphyte fertilzer spray weekly, or according to package directions.Description: Air plants put down no roots and receive nutrients and moisture through their leaves. Once an air plant blooms, it will produce offshoots that will become new plants in one to two years. illandsia is a genus of around 650 species of evergreen, perennial flowering plants in the family Bromeliaceae, native to the Neotropics. Most species are epiphytes, meaning they grow on other plants, but some are aerophytes, growing on shifting desert soil. They use crassulacean acid metabolism (CAM) to photosynthesize, closing their stomata during the day to prevent water loss and opening them at night to absorb carbon dioxide.",
  },
  {
    name: "Fiddle Leaf Fig",
    image: "FIDDLE LEAF",
    plantId: 32,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "FiddleLeafFigDetails",
    description: "Size: Up to 10 feet tall.Water: From spring to fall, water when the top inch of soil feels dry, more sparingly in winter.Fertilize: Apply a high-nitrogen fertilizer that includes micronutrients monthly from spring through fall. Don't feed during winter months.Description: Fiddle-leaf figs instantly give any room a jungle-like vibe. They grow very slowly, but can eventually reach the ceiling. With a reputation for being finicky, this cold-sensitive rainforest native needs just the right conditions to thrive indoors. Prefers east-facing, sunny windows; unobstructed late day sun in a west- or south-facing window may burn the leaves. This evergreen tree can grow 25 to 50 feet tall in its native habitat. It produces large, 8 to 15-inch-long, dull green, thick, fiddle-shaped leaves.",
  },
  {
    name: "Monstera",
    image: "MONSTERA",
    plantId: 33,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "MonsteraDetails",
    description: "Size: 3 to 20 feet tall.Water: Deeply water every 1 to 2 weeks, or whenever the soil feels dry. Drooping leaves often mean your plant needs a drink.Fertilize: Not necessary, but an occasional dose of all-purpose houseplant food during the spring and summer will encourage more vigorous growth.Description: Popular houseplants prized for their unique, holed leaves. They come in various types, sizes, and growth habits, making them versatile for indoor decor. Monsteras add a tropical touch to spaces and are suitable for different growing styles. Monstera deliciosa, commonly called Swiss Cheese Plant, is a climbing vine native to Mexico and Panama. It exhibits negative phototropism in its seedling stage, growing towards darker areas which indicates the base of a larger tree to climb. Monstera can produce edible fruit that tastes like a cross between jackfruit and pineapple, but the fruit is poisonous until completely ripe.",
  },
  {
    name: "Polka Dot Plant",
    image: "POLKA DOT PLANT",
    plantId: 34,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "PolkaDotPlantDetails",
    description: "Size: Up to 12 inches tall.Water: Keep the soil consistently moist, but not soggy. Too little water causes the leaves to wilt.Fertilize: Apply a diluted liquid fertilizer every two weeks from early spring through late summer.Description: A charming little foliage plant with cheery pink speckles over deep-green leaves. In addition to pink, cultivars sporting white or red dots are also available. Pinch back the stems of too tall or leggy plants to encourage bushier growth. Native to Madagascar, other species in this genus are found in South Africa and Southeast Asia. It is a bushy plant with oval, softly downy leaves.",
  },
  {
    name: "Rubber Plant",
    image: "RUBBER PLANT",
    plantId: 35,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "RubberPlantDetails",
    description: "Size: Up to 10 feet tall.Water: Keep soil evenly moist. Water when it becomes slightly dry to the touch.Fertilize: Fertilize every two weeks when actively growing from spring through fall; monthly in winter.Description:  Rubber plants can threaten to outgrow a room, but can be kept in check by pruning off the top at the central stem. This will encourage growth of side branches. Keeping your plant in a smaller pot will also curb its growth. The rubber plant is a broadleaf evergreen flowering tree in the Mulberry family. In the wild, it can reach up to 100 feet high. The species name 'elastica' refers to the milky sap that was historically used to produce rubber. It prefers to remain in one location and does not do well with drafts or cold temperatures.",
  },
  {
    name: "Tradescantia",
    image: "TRADESCANTIA",
    plantId: 36,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "TradescantiaDetails",
    description: "Size: 3 to 36 inches tall, 9 to 24 inches wide, can trail to 36 inches.Water: Tradescantias prefer moist soil, but avoid overwatering to prevent root rot.Fertilize: Use a balanced liquid houseplant fertilizer monthly.Description:  An easy-to-grow, trailing plant that is great for beginners. Perfect for use in a hanging basket or even spilling from a regular planter. If your plant becomes leggy over time, prune it back by pinching off the stems directly above a leaf node. This plant is part of a genus that includes various species known for their trailing habit. They are often grown for their colorful foliage.",
  },
  {
    name: "Watermelon Peperomia",
    image: "WATERMELON PEPEROMIA",
    plantId: 37,
    plantLevel: 1,
    waterLevel: 0.1,
    lightLevel: 0.1,
    fertilizerLevel: 0.1,
    points: 0,
    waterStock: 10,
    lightStock: 10,
    fertilizerStock: 10,
    screen: "WatermelonPeperomiaDetails",
    description: "Size: 6 to 8 inches tall.Water: Water moderately, allowing the soil to become dry to the touch before rewatering. Overwatering can cause root rot.Fertilize: Apply a balanced 20-20-20 liquid fertilizer monthly during the growing season, from mid-March to November. Cease fertilizing in winter when plant growth slows down.Description:  Looking like a potful of mini watermelons atop red stems, this green-and-silver striped peperomia begs to be noticed. A nearly foolproof houseplant for beginners, it rarely needs repotting and doesn’t mind a bit of neglect. This peperomia is visually distinct with its green-and-silver striped leaves and red stems. It is a nearly foolproof houseplant.",
  }
];

